### PR TITLE
[fix]: fix jitter, ping page fetch error

### LINKED ISSUE #348: Bug: Ping and Jitter routes not working as expected
**Describe the bug**
The `/ping` and `/jitter` routes do not display the charts upon selecting the routes from the input.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/ping` or `/jitter`. You can navigate from Testing Tools in the sidebar menu.
2. Select a route from the select input.
3. No charts/information is displayed.
4. See error: `index.js:1451 SyntaxError: Unexpected token I in JSON at position 0` in the console.

**Expected behaviour**
The Ping/Jitter charts should be displayed for the selected route.

**Screenshots**
Screenshot from 2021-03-13 18-15-42

**Desktop:**
 - OS: Ubuntu
 - Version 20.04

### PR DESCRIPTION
**Pull request by geforce6t**
**What does this do ?**
Fetches the value for jitter and ping pages correctly to be displayed through the charts.

Fix #348 

Current State: 
Screenshot from 2021-03-16 00-14-37
Screenshot from 2021-03-16 00-17-32

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
@geforce6t I am getting INVALID_PATH in some dropdowns. Can you please check that and if the data does not exist, then it should show data not found or something similar that was done in #332 .

Screenshot from 2021-03-20 17-08-57

**Comment by geforce6t** [comment]
After handling invalid paths
Screenshot from 2021-03-20 22-52-51
Screenshot from 2021-03-20 22-53-08

**Review by Harkishen-Singh — APPROVED** [review]
LGTM! Thank you.

**Review by muskankhedia — APPROVED** [review]

**Pull request merged**
