### PR TITLE
feat: improve label ui

### PR DESCRIPTION
**Pull request by sachdeva-shrey**
Signed-off-by: sachdeva-shrey <shreysachdeva.2000@gmail.com>

Fixes https://github.com/bench-routes/bench-routes/issues/358

## Changes
- Improved the Add Label UI

## Screenshots

Screenshot from 2021-03-20 13-46-25

Screenshot from 2021-03-20 13-44-40

### CODE REVIEW

**Comment by aquibbaig** [comment]
@sachdeva-shrey This is great! The labels as of now look like a weird design, so I'm looking forward to the changes.

**Comment by sachdeva-shrey** [comment]
@aquibbaig Sure, I've added some styles and updated the screenshot in the description. Please let me know if it's better now.

**Review by muskankhedia — APPROVED** [review]
LGTM! Thank you for the PR.

**Comment by muskankhedia** [comment]
@sachdeva-shrey Can you please rebase the PR with the master branch?

**Comment by sachdeva-shrey** [comment]
@muskankhedia Sure, would you like me to squash the commits? It doesn't have any conflicts with `master`.

**Comment by muskankhedia** [comment]
> @muskankhedia Sure, would you like me to squash the commits? It doesn't have any conflicts with `master`.

You can just merge the master branch, that is just as a safety measure to any conflicts. Also, if you can squash all the commits it will surely be a plus point.

**Comment by sachdeva-shrey** [comment]
@muskankhedia Sure, I've rebased and squashed the commits.

**Pull request merged**
