### PR TITLE
created dockerignore file | Solves #385

### PR DESCRIPTION
**Pull request by Anuragtech02**
### What was the issue ?
Dockerfile was huge  (380MB), size should be significantly less.

### Before Adding `.dockerignore` size was `389.4MB`
SS_BEFORE

### After adding `.dockerignore` size became `40.86MB`
SS_AFTER

### What does this PR do ?
Solves #385 
- Creates a `.dockerignore` in the root directory.
- Creates a copy of `.gitignore` + some code to remove `node_modules`.

### CODE REVIEW

**Comment by Anuragtech02** [comment]
@muskankhedia  Please let me know if this requires any changes.

**Comment by muskankhedia** [comment]
@Anuragtech02 I feel you have copied the `.gitignore` file, but our `.gitignore` file hasn't been updated for a year and now many of the paths don't even exist. Can you please update it based on the present code?

**Comment by Anuragtech02** [comment]
@muskankhedia Sure I'll update the paths.

**Comment by Anuragtech02** [comment]
@muskankhedia Should I also update the paths in `.gitignore` or should I open a separate PR for that ?

**Comment by muskankhedia** [comment]
@Anuragtech02 You can update it in the same PR.

**Review by muskankhedia — CHANGES_REQUESTED** [review]
Please avoid making changes to `go.mod` and `go.sum` file.

**Comment by Anuragtech02** [comment]
> @Anuragtech02 I feel you have copied the `.gitignore` file, but our `.gitignore` file hasn't been updated for a year and now many of the paths don't even exist. Can you please update it based on the present code?

@muskankhedia Fortunately there were not many paths that were incorrect. Only two were incorrect namely `dashboard/node_modules` & `dashboard/package-lock.json` to which I added `v1.1` so now they're `dashboard/v1.1/package-lock.json`. 

I haven't added anything new to `.gitignore`, please let me know if there is something to be added.

**Comment by Anuragtech02** [comment]
> Please avoid making changes to `go.mod` and `go.sum` file.

Actually I didn't make any change to those files, I was just trying to run the project using the steps given in the installation readme, so probably that changed them.

**Comment by muskankhedia** [comment]
> > Please avoid making changes to `go.mod` and `go.sum` file.
> 
> Actually I didn't make any change to those files, I was just trying to run the project using the steps given in the installation readme, so probably that changed them.

Yes, that can be the case. Can you please revert the changes to those files?

**Comment by Anuragtech02** [comment]
> > > Please avoid making changes to `go.mod` and `go.sum` file.
> > 
> > 
> > Actually I didn't make any change to those files, I was just trying to run the project using the steps given in the installation readme, so probably that changed them.
> 
> Yes, that can be the case. Can you please revert the changes to those files?

Instead of reverting should I just replace the files with the older ones ?

**Comment by Anuragtech02** [comment]
@muskankhedia  I've reverted changes in the files `go.mod` & `go.sum`

**Review by muskankhedia — APPROVED** [review]

**Comment by muskankhedia** [comment]
Thank you for the PR!

**Pull request merged**
