### PR TITLE
Added Message field to send appropriate messages from API

### LINKED ISSUE #337: send appropriate messages from the API
Rather than throwing an error on the console on errors or just a "success" alert on success , let's send an appropriate message from the API and display it as a toast alert on the dashboard.
Currently, we send the API interface in the form of a byte array.
An approach to this problem, IMHO will be to have an interface for `response_object` and populate the same before sending it. It can contain some primitive parameters such as `Data/Body`, `Message`, etc.

### PR DESCRIPTION
**Pull request by Rits1272**
Signed-off-by: rits1272 ritikjain1272@gmail.com

File Changed: `api.go`

 ### Changes
 - Added `Message` field in the response to send appropriate messages from the API
 - This `message` can then be displayed as a `toast` in the dashboard   
 - The errors which were handled using `panic`, an appropriate message has been added and sent to the frontend 
 - Uptil this commit, no changes have been made in the frontend. Once get approval for the API changes, complimentary changes can be made at the frontend side either in this PR or a new PR

Resolves #337

### CODE REVIEW

**Comment by Rits1272** [comment]
Kindly review @Harkishen-Singh @aquibbaig :)

**Review by muskankhedia — CHANGES_REQUESTED** [review]
@Rits1272 Can you please revert the changes in all other files except `api.go`?

**Comment by Rits1272** [comment]
Kindly check @muskankhedia

**Review by aquibbaig — CHANGES_REQUESTED** [review]
Please keep the following in mind:
- Your commits should be precise in the description and should exactly define what it says. (please remove jargons such as "fix" and "ci-fix")
- Rather than having commits on top, it's better to edit commits that overlap on the same change. (if you did a CI fix again, add it to the previous CI fix other than making another commit as "CI fix", I'd say remove all the commits than those necessary).
- Having multiple commits will just make the review process slower and your commits will be squashed if they do not uniquely solve a different issue.

**Comment by Rits1272** [comment]
Having merge conflicts while rebasing. Hate to say this but I will create a new PR for the same

**Comment by Rits1272** [comment]
> Please keep the following in mind:
> 
> * Your commits should be precise in the description and should exactly define what it says. (do not use jargons such as "fix" and "ci-fix")
> * Rather than having commits on top, it's better to edit commits that overlap on the same change. (if you did a CI fix again, add it to the previous CI fix other than making another commit as "CI fix", I'd say remove all the commits than those necessary).
> * Having multiple commits will just make the review process slower and your commits will be squashed if they do not uniquely solve a different issue.
> * Never commit `node_modules`!

I will definitely keep these in mind for sure @aquibbaig and will try to write better commit messages and squash them if necessary. Thanks!

**Pull request closed without merging**
