### PR TITLE
Fix: Remove white-dash in Tab component

### PR DESCRIPTION
**Pull request by iamkryptonite**
Description: Added outline style to Tabs component to remove white dashed-line after clicking.
Signed off by: @iamkryptonite thesatyakidas.00220033@gmail.com
Fixes: #349 
Proof:
ezgif com-video-to-gif

### CODE REVIEW

**Comment by iamkryptonite** [comment]
@Harkishen-Singh this PR is ready for review.

**Review by muskankhedia — CHANGES_REQUESTED** [review]
@iamkryptonite The changes look good to me. Can you implement the same for the `Monitoring` screen tabs as well. 

Screenshot 2021-03-14 at 7 59 36 PM

Also can you undo the changes in the `go.mod` file and `go.sum` file.

**Comment by iamkryptonite** [comment]
> @iamkryptonite The changes look good to me. Can you implement the same for the `Monitoring` screen tabs as well?
> 
> Screenshot 2021-03-14 at 7 59 36 PM
> 
> Also can you undo the changes in the `go.mod` file and `go.sum` file.

Sure.

**Comment by iamkryptonite** [comment]
> @iamkryptonite The changes look good to me. Can you implement the same for the `Monitoring` screen tabs as well?
> 
> Screenshot 2021-03-14 at 7 59 36 PM
> 
> Also can you undo the changes in the `go.mod` file and `go.sum` file.

Sure

**Review by Harkishen-Singh — APPROVED** [review]
I think this is good. @muskankhedia can you please give a final look before we merge this?

**Review by muskankhedia — APPROVED** [review]

**Pull request merged**
