### PR TITLE
Reducing redundancy in data structures

### PR DESCRIPTION
**Pull request by Tushar3099**
Signed-off-by: Tushar3099 <tusharneogi30@gmail.com>

Fixes Issue: #299 

**Type Of Change**
----

- [x] Clean Up

**Changes**
----

- Refactored the redundant fields that were used in different data structures.
- Deleted fields from higher-level data structures that can be accessed from lower-level data structures.

### CODE REVIEW

**Comment by Tushar3099** [comment]
@Harkishen-Singh  Please review my PR. I am not sure why there is a CI issue. On local everything worked fine.

**Review by aquibbaig — APPROVED** [review]
LGTM

**Comment by aquibbaig** [comment]
Not sure if we could rename `Ping` -> `PingDataValue` or something which signifies that the struct contains the data points collected by the Ping module.

**Comment by Tushar3099** [comment]
@aquibbaig, of course, changing the name from `Ping` to something more meaningful like `PingDataValue` will be more reasonable. If you say I can make the changes.

**Comment by Harkishen-Singh** [comment]
@aquibbaig I think Ping is enough. Otherwise, if we want the struct to speak themselves as they are representatives of values, then all other struct's will have to be changed to xDataValues where x can be FloodPing, Jitter, etc. 

@Tushar3099 this PR looks good. I will take a closer look shortly. Thank you.

**Review by Harkishen-Singh — APPROVED** [review]
LGTM! Thank you for the PR.

**Pull request merged**
