### PR TITLE
fix: Support for ping in windows machine

### PR DESCRIPTION
**Pull request by muskankhedia**
To be merged after PR #508

### CODE REVIEW

**Comment by muskankhedia** [comment]
@satyaarthchhabra I have fixed the issue for the golang server in the windows machine. Please check it out and let me know if there are still some errors.

**Comment by satyaarthchhabra** [comment]
hi  @muskankhedia  i tried running it using wsl and the errors are still same . here are the logs (https://pastebin.com/wPma29eG)

**Comment by aquibbaig** [comment]
@satyaarthchhabra Does the command `ping google.com` work as expected in your cmd?

**Comment by muskankhedia** [comment]
Merging the PR to support ping for the windows system.

**Comment by muskankhedia** [comment]
> hi @muskankhedia i tried running it using wsl and the errors are still same . here are the logs (https://pastebin.com/wPma29eG)

WSL might provide some error, please try running in local.

**Pull request merged**
