### PR TITLE
Quick-input icon Redesigning

### PR DESCRIPTION
**Pull request by Tushar3099**
Signed-off-by: Tushar3099 <tusharneogi30@gmail.com>

Fixes Issue: #399

**Type Of Change**
----

- [x] Bug

**Changes**
----

- Redesigned Quick-input Icon.
- When we hover over the icon, it slides out as Quick-Input.

**Preview**
----

https://user-images.githubusercontent.com/51849085/111923182-fa729080-8ac3-11eb-9b83-8ef182aa028c.mp4

### CODE REVIEW

**Comment by Tushar3099** [comment]
@muskankhedia Please review my PR.

**Comment by Tushar3099** [comment]
@muskankhedia Please review my PR.

**Comment by muskankhedia** [comment]
@Tushar3099 The implementation looks good but still, the issue related to the hiding pagination features exist.

Screenshot 2021-03-25 at 9 06 05 AM

**Comment by Tushar3099** [comment]
@muskankhedia Yeah it somehow depends on window size, but in this design we can move the icon upwards so that pagination will not collide anymore.
Shall i make the changes and update the PR.

**Comment by muskankhedia** [comment]
yes, that will be helpful.

**Comment by Tushar3099** [comment]
@muskankhedia I have made the prescribed changes

**Review by muskankhedia — APPROVED** [review]
LGTM! Thank you for the PR.

**Pull request merged**
