### PR TITLE
Fix spacing of cards on config page

### LINKED ISSUE #397: Cards on Configuration page not spaced correctly
**Describe the bug**
Currently the horizontal alignment of the cards doesnt look good as a large space is left on the right side.

Screenshot from 2021-03-20 00-55-38

### PR DESCRIPTION
**Pull request by ruddi10**
Signed-off-by: ruddi <rudrakshaggarwalsachin@gmail.com>
fixes #397 

Screenshot from 2021-03-20 00-55-59

### CODE REVIEW

**Comment by ruddi10** [comment]
@muskankhedia kindly review it

**Comment by muskankhedia** [comment]
@ruddi10 Thank you for the PR but I don't see anywhere this design look better than the previous one. Also, the design before looks quite simple and good. Hence, closing the PR and issue for now.

**Comment by ruddi10** [comment]
@muskankhedia so was that space intentional?

**Comment by muskankhedia** [comment]
yes

**Pull request closed without merging**
